SELECT
    I.REST_ID,
    I.REST_NAME,
    I.FOOD_TYPE,
    I.FAVORITES,
    I.ADDRESS,
    TO_NUMBER(TO_CHAR(ROUND(AVG(R.REVIEW_SCORE), 2), 'FM0.00')) AS SCORE
FROM 
    REST_INFO I
    JOIN REST_REVIEW R ON I.REST_ID = R.REST_ID
WHERE
    I.ADDRESS LIKE '서울%'
GROUP BY
    I.REST_ID,
    I.REST_NAME,
    I.FOOD_TYPE,
    I.FAVORITES,
    I.ADDRESS
ORDER BY
    AVG(R.REVIEW_SCORE) DESC,
    I.FAVORITES DESC
;